import { Box, Card, CardBody, Grid, GridItem, Text } from '@chakra-ui/react';
import { RaffleCard } from '@r/components/RaffleCard';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Rifa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main" maxW={1200} p={4} m="0 auto">
        <RaffleCard />
      </Box>
    </>
  );
}
