import Head from 'next/head';

import { Box } from '@chakra-ui/react';

import { RaffleCard } from '@r/components/RaffleCard';
import { Header } from '@r/components/header';
import { RaffleRegisterModal } from '@r/components/RaffleRegisterModal';
import { Raffle } from '@r/components/Raffle';

export default function Home() {
  return (
    <>
      <Head>
        <title>Rifa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <script src="/static/confetti.js" defer></script>
      </Head>
      <Box as="main" h="100%" maxW={1200} p={[2, 2, 8]} m="0 auto">
        {/** <Header /> **/}
        <RaffleCard />
        <RaffleRegisterModal />
        <Raffle />
      </Box>
    </>
  );
}
